language: android
dist: trusty
android:
  components:
    - build-tools-29.0.2
    - android-29
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository