language: android
dist: trusty
jdk: openjdk8
sudo: false

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # to install Android SDK tools
    - platform-tools
    - build-tools-29.0.3
    - android-29

before_install:
  - yes | sdkmanager "platforms;android-29"

script:
   - ./gradlew build connectedCheck